#!/usr/local/sbin/charm-env python3

from charmhelpers.core.hookenv import (
    action_set,
    action_fail
)

from charmhelpers.fetch import (
    apt_install,
    apt_update,
    apt_hold,
    apt_unhold
)

from charmhelpers.core import host
from charmhelpers.core.templating import render

from reactive.docker import (
    docker_packages,
    determine_apt_source,
    recycle_daemon
)


def main():
    """
    :return: None
    """
    try:
        apt_update(fatal=True)

        runtime = determine_apt_source()
        apt_unhold(docker_packages[runtime])
        apt_install(
            docker_packages[runtime],
            options=['-o Dpkg::Options::=--force-confnew'],
            fatal=True
        )
        apt_hold(docker_packages[runtime])

        recycle_daemon()

        action_set({
            'runtime': ', '.join(docker_packages[runtime])
        })

    except Exception as e:
        action_fail(e)


if __name__ == '__main__':
    main()